from init_env import init_environment

env = init_environment("mlibrary qt5 geant4 clhep")

# calling SConscript here to build just the library as in the hierarchy build
libs    = SConscript('SConscript', exports='env')
libsDLL = SConscript('SConscriptDLL')

Depends(libsDLL,  libs);
