from init_env import init_environment

env = init_environment("mlibrary qt5 geant4 clhep")

sources = Split("""
	gvolume.cc
	utilities.cc
	gsystem.cc
	systemFactories/registerFactory.cc
	systemFactories/text/gmaterial.cc
	systemFactories/text/gvolume.cc
	""")

lib = env.Library(source = sources, target = "../lib/gvolume")
