from init_env import init_environment

env = init_environment("mlibrary qt5")

sources = Split("""
	gVolume.cc
	utilities.cc
	gSystem.cc
	""")

lib = env.Library(source = sources, target = "../lib/gVolume")
