from init_env import init_environment

env = init_environment("qt5 mlibrary")
# manually appending this library so the example can be compiled
# the environment will not load the library if it's not there
env.Append(LIBS = 'qtButtonsWidget')

# calling SConscript here to build just the library as in the hierarchy build
lib = SConscript('SConscript')

example_sources = Split("""
	example.cc
	exampleResources.qrc""")

example = env.Program(source = example_sources, target = "example")

Depends(example,  lib);
