from init_env import init_environment

env = init_environment("mlibrary qt5 geant4 clhep")

# calling SConscript here to build just the library as in the hierarchy build
gdLib = SConscript('SConscript', exports='env')


ctof_dll  = env.SharedLibrary( source = "ctofRoutinesExample.cc",  target = "ctofRoutinesExample")
Depends(ctof_dll,  gdLib);


example_sources = Split("""
	example.cc
	""")
example = env.Program(source = example_sources, target = "example")

Depends(example,  ctof_dll);
