from init_env import init_environment

env = init_environment("mlibrary qt5 geant4 clhep")

ctof_dll  = env.SharedLibrary( source = "ctofRoutinesExample.cc",  target = "ctofRoutinesExample")

example_sources = Split("""
	example.cc
	""")

example = env.Program(source = example_sources, target = "example")

