from init_env import init_environment

sources = Split("""
	trueObservable.cc
	truePulse.cc
	""")


env = init_environment("qt5 mlibrary geant4 clhep")
lib = env.Library(source = sources, target = "../lib/gruns")
