#!/bin/csh -f

rm -rf cadmeshBuild
mkdir cadmeshBuild
cd cadmeshBuild

# setting
set ncpu = `getconf _NPROCESSORS_ONLN`
set opt = " -j"$ncpu" "

cmake ../cadmesh -DCMAKE_INSTALL_PREFIX:PATH=$MLIBRARY
make $opt install

# removing unnecessary files so we can make cadmesh part of mlibrary
# rm -rf external/assimp/CMakeLists.txt
# rm -rf external/assimp/.git
# rm -rf external/assimp/test
# rm -rf external/tetgen/.git
