#!/bin/csh -f

rm -rf cadmeshBuild
mkdir cadmeshBuild
cd cadmeshBuild

# setting
set ncpu = `getconf _NPROCESSORS_ONLN`
set opt = " -j"$ncpu" "

echo
echo Compiling with options $opt
echo

cmake ../cadmesh -DCMAKE_INSTALL_PREFIX:PATH=$MLIBRARY
make $opt install
echo done

