#!/bin/csh -f



if($#argv != 1) then
        echo " "
        echo "Usage:   "
        echo  "  >> createMLibrary libraryName"
        echo " "
        exit 0
endif


set library = $1
set templateLibrary = textProgressBar

mkdir $library


foreach p (SConstruct SConscript  example.cc settings.xcconfig Doxyfile README.md)
	cp $templateLibrary/$p $library/
end

foreach p (changelog todo)
	touch $library/$p
end

set header = $library"_h"

set cheader =  `echo $header | tr "[:lower:]" "[:upper:]"`

touch $library/$library".cc"

echo "#ifndef " $cheader       > $library/$library".h"
echo "#define " $cheader " 1" >> $library/$library".h"
echo                          >> $library/$library".h"
echo                          >> $library/$library".h"
echo "class $library {"       >> $library/$library".h"
echo                          >> $library/$library".h"
echo                          >> $library/$library".h"
echo  "};"                    >> $library/$library".h"
echo                          >> $library/$library".h"
echo                          >> $library/$library".h"
echo "#endif"                 >> $library/$library".h"

foreach f(README.md Doxyfile example.cc SConscript SConstruct)
	sed -i '' s/textProgressBar/$library/g     $library/$f
	sed -i '' s/TextProgressBar/$library/g     $library/$f
	sed -i '' s/"Text Progress Bar"/$library/g $library/$f
	sed -i '' s/"text progress bar"/$library/g $library/$f
end

echo "// $library "              > $library/$library".cc"
echo '#include "'$library'.h"'  >> $library/$library".cc"


