#!/bin/csh -f

# cadmesh is coming from:
# git clone https://github.com/christopherpoole/CADMesh.git cadmesh
# it requires two additional submodules, that are fetched during the cmake (unless they are already there, which we want).
# setenv GIT_SSL_NO_VERIFY false < in case the git fetch ssl is not working

# These steps are do
# 1. make sure you get the latest cadmesh release: https://github.com/christopherpoole/CADMesh.git
# 2. untar, move it to cadmesh
# 3. commit changes to mlibrary
# 4. after compiling, commit changes of include to the mlibrary
#
# The following is not working, and leaving cadmesh using this as external for now:
#
# 3. add the assimp release: https://github.com/assimp/assimp/releases (check .gitmodules)
# 3.5 move the release untar into assimp, then remove the tar file
# 4. add the tetgen releases: https://github.com/christopherpoole/tetgen/releases (check .gitmodules)
# 4.5 move the release untar into assimp, then remove the tar file
# 5. commit changes to mlibrary

rm -rf cadmesh

set cadMeshV=1.1
set assimpV=4.1.0
set tetgenV=1.5

set cadMeshF=v$cadMeshV.tar.gz
set assimpF=v$assimpV.tar.gz
set tetgenF=v$tetgenV.tar.gz

set cadmeshR=https://github.com/christopherpoole/CADMesh/archive/$cadMeshF
set assimpR=https://github.com/assimp/assimp/archive/$assimpF
set tetgenR=https://github.com/christopherpoole/tetgen/archive/$tetgenF


# cadmesh
wget $cadmeshR
mkdir cadmesh
tar -zxpf $cadMeshF  --strip-components 1 -C cadmesh
rm $cadMeshF
cd cadmesh


# assimp
#wget $assimpR
#mkdir -p external/assimp
#tar -zxpf $assimpF  --strip-components 1 -C external/assimp
#rm $assimpF
#rm -rf assimp/test

# tetgen
#wget $tetgenR
#mkdir -p external/tetgen
#tar -zxpf $tetgenF  --strip-components 1 -C external/tetgen
#rm $tetgenF



