#!/bin/csh -f

# cadmesh is coming from:
# git clone https://github.com/christopherpoole/CADMesh.git cadmesh
# it requires two additional submodules, that are fetched during the cmake (unless they are already there).
# setenv GIT_SSL_NO_VERIFY false

rm -rf cadmeshBuild
mkdir cadmeshBuild
cd cadmeshBuild

cmake ../cadmesh -DCMAKE_INSTALL_PREFIX:PATH=$MLIBRARY
make -j4 install
