from init_env import init_environment

env = init_environment("mlibrary qt5 geant4 clhep")

sources = Split("""
	g4volume.cc
	utilities.cc
	world.cc
	g4systemFactories/registerFactory.cc
	g4systemFactories/getG4Volumes.cc
	g4systemFactories/checkDependencies.cc
	g4systemFactories/native/g4SolidConstructorDescription.cc
	g4systemFactories/native/checkAndReturnParameters.cc
	g4systemFactories/native/solid.cc
	g4systemFactories/native/logical.cc
	g4systemFactories/native/physical.cc
	g4systemFactories/cad/solid.cc
	g4systemFactories/cad/logical.cc
	g4systemFactories/cad/physical.cc
	""")

lib = env.Library(source = sources, target = "../lib/g4volume")
