from init_env import init_environment

env = init_environment("qt5 clas12")


# Utilities
option_sources = Split("""
	options.cc
	""")
lib = env.Library(source = option_sources, target = "../lib/option")


example = env.Program(source = "example.cc", target = "example")

Depends(example,  lib);
