from init_env import init_environment

env = init_environment("ccdb mlibrary")
# manually appending this library so the example can be compiled
# the environment will not load the library if it's not there
env.Append(LIBS = 'translationTable')

lib = env.Library(source = "translationTable.cc", target = "../lib/translationTable")

example = env.Program(source = "example.cc", target = "example")

Depends(example,  lib);
