from init_env import init_environment

env = init_environment("mlibrary")

# Library
option_sources = Split("""
	translationTable.cc
	""")
lib = env.Library(source = option_sources, target = "../lib/translationTable")

example = env.Program(source = "example.cc", target = "example")

