from init_env import init_environment

env = init_environment("mlibrary qt5 clhep geant4")

# manually appending this library so the example can be compiled
# the environment will not load the library if it's not there
env.Append(LIBS = 'ghit')

# calling SConscript here to build just the library as in the hierarchy build
lib = env.SConscript('SConscript', exports='env')

# apparently the example compilation is required so that the display library is installed
example = env.Program(source = "example.cc", target = "example")
Depends(example,  lib);

