from init_env import init_environment

env = init_environment("mlibrary qt5 geant4 clhep")

sources = Split("""
	g4display.cc
	utilities.cc
	""")

lib = env.Library(source = sources, target = "../lib/g4display")
