from init_env import init_environment

env = init_environment("mlibrary geant4 clhep qt5")


sources = Split("""
	observables/gobservables.cc
	""")

lib  = env.Library(source = sources, target = "../lib/gdata")

