from init_env import init_environment

env = init_environment("qt5 mlibrary")
# manually appending this library so the example can be compiled
# the environment will not load the library if it's not there
env.Append(LIBS = 'gsplash')


# Library
gsplash_sources = Split("""
	gsplash.cc
	""")
lib = env.Library(source = gsplash_sources, target = "../lib/gsplash")

example = env.Program(source = "example.cc", target = "example")

Depends(example,  lib);
